// Code generated by protoc-gen-go.
// source: golpje.proto
// DO NOT EDIT!

/*
Package golpje is a generated protocol buffer package.

It is generated from these files:
	golpje.proto

It has these top-level messages:
	Empty
	ProtoShow
	ProtoEvent
	ProtoEpisode
	ProtoEvents
	EventRequest
	ProtoShows
	ProtoEpisodes
	ShowRequest
	AddShowResponse
	EpisodeRequest
	AddEpisodeResponse
*/
package golpje

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProtoShow struct {
	ID            string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Regexp        string `protobuf:"bytes,3,opt,name=Regexp" json:"Regexp,omitempty"`
	Active        bool   `protobuf:"varint,4,opt,name=Active" json:"Active,omitempty"`
	Episodeidtype string `protobuf:"bytes,5,opt,name=Episodeidtype" json:"Episodeidtype,omitempty"`
	Minimal       uint32 `protobuf:"varint,6,opt,name=Minimal" json:"Minimal,omitempty"`
}

func (m *ProtoShow) Reset()                    { *m = ProtoShow{} }
func (m *ProtoShow) String() string            { return proto.CompactTextString(m) }
func (*ProtoShow) ProtoMessage()               {}
func (*ProtoShow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoShow) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProtoShow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProtoShow) GetRegexp() string {
	if m != nil {
		return m.Regexp
	}
	return ""
}

func (m *ProtoShow) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *ProtoShow) GetEpisodeidtype() string {
	if m != nil {
		return m.Episodeidtype
	}
	return ""
}

func (m *ProtoShow) GetMinimal() uint32 {
	if m != nil {
		return m.Minimal
	}
	return 0
}

type ProtoEvent struct {
	ID        string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Timestamp int64    `protobuf:"varint,2,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Related   []string `protobuf:"bytes,3,rep,name=related" json:"related,omitempty"`
	Data      string   `protobuf:"bytes,4,opt,name=Data" json:"Data,omitempty"`
}

func (m *ProtoEvent) Reset()                    { *m = ProtoEvent{} }
func (m *ProtoEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtoEvent) ProtoMessage()               {}
func (*ProtoEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProtoEvent) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProtoEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ProtoEvent) GetRelated() []string {
	if m != nil {
		return m.Related
	}
	return nil
}

func (m *ProtoEvent) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ProtoEpisode struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=Title" json:"Title,omitempty"`
	Showid      string `protobuf:"bytes,3,opt,name=Showid" json:"Showid,omitempty"`
	Added       int64  `protobuf:"varint,4,opt,name=Added" json:"Added,omitempty"`
	Magnetlink  string `protobuf:"bytes,5,opt,name=Magnetlink" json:"Magnetlink,omitempty"`
	Episodeid   string `protobuf:"bytes,6,opt,name=Episodeid" json:"Episodeid,omitempty"`
	Downloaded  bool   `protobuf:"varint,7,opt,name=Downloaded" json:"Downloaded,omitempty"`
	Downloading bool   `protobuf:"varint,8,opt,name=Downloading" json:"Downloading,omitempty"`
}

func (m *ProtoEpisode) Reset()                    { *m = ProtoEpisode{} }
func (m *ProtoEpisode) String() string            { return proto.CompactTextString(m) }
func (*ProtoEpisode) ProtoMessage()               {}
func (*ProtoEpisode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtoEpisode) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProtoEpisode) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ProtoEpisode) GetShowid() string {
	if m != nil {
		return m.Showid
	}
	return ""
}

func (m *ProtoEpisode) GetAdded() int64 {
	if m != nil {
		return m.Added
	}
	return 0
}

func (m *ProtoEpisode) GetMagnetlink() string {
	if m != nil {
		return m.Magnetlink
	}
	return ""
}

func (m *ProtoEpisode) GetEpisodeid() string {
	if m != nil {
		return m.Episodeid
	}
	return ""
}

func (m *ProtoEpisode) GetDownloaded() bool {
	if m != nil {
		return m.Downloaded
	}
	return false
}

func (m *ProtoEpisode) GetDownloading() bool {
	if m != nil {
		return m.Downloading
	}
	return false
}

type ProtoEvents struct {
	Events []*ProtoEvent `protobuf:"bytes,1,rep,name=Events" json:"Events,omitempty"`
}

func (m *ProtoEvents) Reset()                    { *m = ProtoEvents{} }
func (m *ProtoEvents) String() string            { return proto.CompactTextString(m) }
func (*ProtoEvents) ProtoMessage()               {}
func (*ProtoEvents) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProtoEvents) GetEvents() []*ProtoEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type EventRequest struct {
	All   bool  `protobuf:"varint,1,opt,name=All" json:"All,omitempty"`
	Since int64 `protobuf:"varint,2,opt,name=Since" json:"Since,omitempty"`
}

func (m *EventRequest) Reset()                    { *m = EventRequest{} }
func (m *EventRequest) String() string            { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()               {}
func (*EventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EventRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

func (m *EventRequest) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

type ProtoShows struct {
	Shows []*ProtoShow `protobuf:"bytes,1,rep,name=Shows" json:"Shows,omitempty"`
}

func (m *ProtoShows) Reset()                    { *m = ProtoShows{} }
func (m *ProtoShows) String() string            { return proto.CompactTextString(m) }
func (*ProtoShows) ProtoMessage()               {}
func (*ProtoShows) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ProtoShows) GetShows() []*ProtoShow {
	if m != nil {
		return m.Shows
	}
	return nil
}

type ProtoEpisodes struct {
	Episodes []*ProtoEpisode `protobuf:"bytes,1,rep,name=Episodes" json:"Episodes,omitempty"`
}

func (m *ProtoEpisodes) Reset()                    { *m = ProtoEpisodes{} }
func (m *ProtoEpisodes) String() string            { return proto.CompactTextString(m) }
func (*ProtoEpisodes) ProtoMessage()               {}
func (*ProtoEpisodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ProtoEpisodes) GetEpisodes() []*ProtoEpisode {
	if m != nil {
		return m.Episodes
	}
	return nil
}

type ShowRequest struct {
	Onlyactive bool   `protobuf:"varint,1,opt,name=Onlyactive" json:"Onlyactive,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *ShowRequest) Reset()                    { *m = ShowRequest{} }
func (m *ShowRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()               {}
func (*ShowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ShowRequest) GetOnlyactive() bool {
	if m != nil {
		return m.Onlyactive
	}
	return false
}

func (m *ShowRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddShowResponse struct {
	Show    *ProtoShow `protobuf:"bytes,1,opt,name=Show" json:"Show,omitempty"`
	Success bool       `protobuf:"varint,2,opt,name=Success" json:"Success,omitempty"`
	Error   string     `protobuf:"bytes,3,opt,name=Error" json:"Error,omitempty"`
}

func (m *AddShowResponse) Reset()                    { *m = AddShowResponse{} }
func (m *AddShowResponse) String() string            { return proto.CompactTextString(m) }
func (*AddShowResponse) ProtoMessage()               {}
func (*AddShowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AddShowResponse) GetShow() *ProtoShow {
	if m != nil {
		return m.Show
	}
	return nil
}

func (m *AddShowResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddShowResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EpisodeRequest struct {
	Showid string `protobuf:"bytes,1,opt,name=Showid" json:"Showid,omitempty"`
	Season uint32 `protobuf:"varint,2,opt,name=Season" json:"Season,omitempty"`
}

func (m *EpisodeRequest) Reset()                    { *m = EpisodeRequest{} }
func (m *EpisodeRequest) String() string            { return proto.CompactTextString(m) }
func (*EpisodeRequest) ProtoMessage()               {}
func (*EpisodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EpisodeRequest) GetShowid() string {
	if m != nil {
		return m.Showid
	}
	return ""
}

func (m *EpisodeRequest) GetSeason() uint32 {
	if m != nil {
		return m.Season
	}
	return 0
}

type AddEpisodeResponse struct {
	Episode *ProtoEpisode `protobuf:"bytes,1,opt,name=Episode" json:"Episode,omitempty"`
	Success bool          `protobuf:"varint,2,opt,name=Success" json:"Success,omitempty"`
	Error   string        `protobuf:"bytes,3,opt,name=Error" json:"Error,omitempty"`
}

func (m *AddEpisodeResponse) Reset()                    { *m = AddEpisodeResponse{} }
func (m *AddEpisodeResponse) String() string            { return proto.CompactTextString(m) }
func (*AddEpisodeResponse) ProtoMessage()               {}
func (*AddEpisodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AddEpisodeResponse) GetEpisode() *ProtoEpisode {
	if m != nil {
		return m.Episode
	}
	return nil
}

func (m *AddEpisodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddEpisodeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "golpje.Empty")
	proto.RegisterType((*ProtoShow)(nil), "golpje.ProtoShow")
	proto.RegisterType((*ProtoEvent)(nil), "golpje.ProtoEvent")
	proto.RegisterType((*ProtoEpisode)(nil), "golpje.ProtoEpisode")
	proto.RegisterType((*ProtoEvents)(nil), "golpje.ProtoEvents")
	proto.RegisterType((*EventRequest)(nil), "golpje.EventRequest")
	proto.RegisterType((*ProtoShows)(nil), "golpje.ProtoShows")
	proto.RegisterType((*ProtoEpisodes)(nil), "golpje.ProtoEpisodes")
	proto.RegisterType((*ShowRequest)(nil), "golpje.ShowRequest")
	proto.RegisterType((*AddShowResponse)(nil), "golpje.AddShowResponse")
	proto.RegisterType((*EpisodeRequest)(nil), "golpje.EpisodeRequest")
	proto.RegisterType((*AddEpisodeResponse)(nil), "golpje.AddEpisodeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Golpje service

type GolpjeClient interface {
	GetEvents(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*ProtoEvents, error)
	GetShows(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ProtoShows, error)
	AddShow(ctx context.Context, in *ProtoShow, opts ...grpc.CallOption) (*AddShowResponse, error)
	DelShow(ctx context.Context, in *ProtoShow, opts ...grpc.CallOption) (*AddShowResponse, error)
	GetEpisodes(ctx context.Context, in *EpisodeRequest, opts ...grpc.CallOption) (*ProtoEpisodes, error)
	AddEpisode(ctx context.Context, in *ProtoEpisode, opts ...grpc.CallOption) (*AddEpisodeResponse, error)
}

type golpjeClient struct {
	cc *grpc.ClientConn
}

func NewGolpjeClient(cc *grpc.ClientConn) GolpjeClient {
	return &golpjeClient{cc}
}

func (c *golpjeClient) GetEvents(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*ProtoEvents, error) {
	out := new(ProtoEvents)
	err := grpc.Invoke(ctx, "/golpje.Golpje/GetEvents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golpjeClient) GetShows(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ProtoShows, error) {
	out := new(ProtoShows)
	err := grpc.Invoke(ctx, "/golpje.Golpje/GetShows", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golpjeClient) AddShow(ctx context.Context, in *ProtoShow, opts ...grpc.CallOption) (*AddShowResponse, error) {
	out := new(AddShowResponse)
	err := grpc.Invoke(ctx, "/golpje.Golpje/AddShow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golpjeClient) DelShow(ctx context.Context, in *ProtoShow, opts ...grpc.CallOption) (*AddShowResponse, error) {
	out := new(AddShowResponse)
	err := grpc.Invoke(ctx, "/golpje.Golpje/DelShow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golpjeClient) GetEpisodes(ctx context.Context, in *EpisodeRequest, opts ...grpc.CallOption) (*ProtoEpisodes, error) {
	out := new(ProtoEpisodes)
	err := grpc.Invoke(ctx, "/golpje.Golpje/GetEpisodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golpjeClient) AddEpisode(ctx context.Context, in *ProtoEpisode, opts ...grpc.CallOption) (*AddEpisodeResponse, error) {
	out := new(AddEpisodeResponse)
	err := grpc.Invoke(ctx, "/golpje.Golpje/AddEpisode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Golpje service

type GolpjeServer interface {
	GetEvents(context.Context, *EventRequest) (*ProtoEvents, error)
	GetShows(context.Context, *ShowRequest) (*ProtoShows, error)
	AddShow(context.Context, *ProtoShow) (*AddShowResponse, error)
	DelShow(context.Context, *ProtoShow) (*AddShowResponse, error)
	GetEpisodes(context.Context, *EpisodeRequest) (*ProtoEpisodes, error)
	AddEpisode(context.Context, *ProtoEpisode) (*AddEpisodeResponse, error)
}

func RegisterGolpjeServer(s *grpc.Server, srv GolpjeServer) {
	s.RegisterService(&_Golpje_serviceDesc, srv)
}

func _Golpje_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolpjeServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/golpje.Golpje/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolpjeServer).GetEvents(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Golpje_GetShows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolpjeServer).GetShows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/golpje.Golpje/GetShows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolpjeServer).GetShows(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Golpje_AddShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoShow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolpjeServer).AddShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/golpje.Golpje/AddShow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolpjeServer).AddShow(ctx, req.(*ProtoShow))
	}
	return interceptor(ctx, in, info, handler)
}

func _Golpje_DelShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoShow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolpjeServer).DelShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/golpje.Golpje/DelShow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolpjeServer).DelShow(ctx, req.(*ProtoShow))
	}
	return interceptor(ctx, in, info, handler)
}

func _Golpje_GetEpisodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolpjeServer).GetEpisodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/golpje.Golpje/GetEpisodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolpjeServer).GetEpisodes(ctx, req.(*EpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Golpje_AddEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoEpisode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolpjeServer).AddEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/golpje.Golpje/AddEpisode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolpjeServer).AddEpisode(ctx, req.(*ProtoEpisode))
	}
	return interceptor(ctx, in, info, handler)
}

var _Golpje_serviceDesc = grpc.ServiceDesc{
	ServiceName: "golpje.Golpje",
	HandlerType: (*GolpjeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _Golpje_GetEvents_Handler,
		},
		{
			MethodName: "GetShows",
			Handler:    _Golpje_GetShows_Handler,
		},
		{
			MethodName: "AddShow",
			Handler:    _Golpje_AddShow_Handler,
		},
		{
			MethodName: "DelShow",
			Handler:    _Golpje_DelShow_Handler,
		},
		{
			MethodName: "GetEpisodes",
			Handler:    _Golpje_GetEpisodes_Handler,
		},
		{
			MethodName: "AddEpisode",
			Handler:    _Golpje_AddEpisode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "golpje.proto",
}

func init() { proto.RegisterFile("golpje.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0xe3, 0xc6, 0xb1, 0x6f, 0x9a, 0x02, 0x43, 0x29, 0x96, 0x85, 0x2a, 0x6b, 0x04, 0x22,
	0x62, 0x51, 0xa1, 0xa2, 0xf2, 0xd8, 0xa0, 0x5a, 0x4a, 0x14, 0x75, 0x51, 0x40, 0x93, 0xfe, 0x80,
	0x89, 0xaf, 0x12, 0x83, 0x63, 0x9b, 0xcc, 0xb4, 0x25, 0x5f, 0xc3, 0xbf, 0xb1, 0xe7, 0x1f, 0xd0,
	0x3c, 0xfc, 0x48, 0x93, 0x0d, 0xec, 0xe6, 0x1c, 0xdf, 0xc7, 0xb9, 0xe7, 0x5e, 0x19, 0x0e, 0xe6,
	0x45, 0x56, 0x7e, 0xc3, 0xd3, 0x72, 0x55, 0x88, 0x82, 0x38, 0x1a, 0xd1, 0x1e, 0x74, 0xc7, 0xcb,
	0x52, 0xac, 0xe9, 0x2f, 0x0b, 0xbc, 0x2f, 0xf2, 0xd3, 0x74, 0x51, 0xdc, 0x91, 0x43, 0xe8, 0x5c,
	0x8e, 0x7c, 0x2b, 0xb4, 0x86, 0x1e, 0xeb, 0x5c, 0x8e, 0x08, 0x81, 0xfd, 0x4f, 0xf1, 0x12, 0xfd,
	0x8e, 0x62, 0xd4, 0x9b, 0x1c, 0x83, 0xc3, 0x70, 0x8e, 0x3f, 0x4b, 0xdf, 0x56, 0xac, 0x41, 0x92,
	0x8f, 0x66, 0x22, 0xbd, 0x45, 0x7f, 0x3f, 0xb4, 0x86, 0x2e, 0x33, 0x88, 0x3c, 0x87, 0xc1, 0xb8,
	0x4c, 0x79, 0x91, 0x60, 0x9a, 0x88, 0x75, 0x89, 0x7e, 0x57, 0xa5, 0x6d, 0x92, 0xc4, 0x87, 0xde,
	0x55, 0x9a, 0xa7, 0xcb, 0x38, 0xf3, 0x9d, 0xd0, 0x1a, 0x0e, 0x58, 0x05, 0xe9, 0x02, 0x40, 0x09,
	0x1c, 0xdf, 0x62, 0x2e, 0xb6, 0x14, 0x3e, 0x03, 0xef, 0x3a, 0x5d, 0x22, 0x17, 0xf1, 0xb2, 0x54,
	0x32, 0x6d, 0xd6, 0x10, 0xb2, 0xea, 0x0a, 0xb3, 0x58, 0x60, 0xe2, 0xdb, 0xa1, 0x3d, 0xf4, 0x58,
	0x05, 0xe5, 0x64, 0xa3, 0x58, 0xc4, 0x4a, 0xab, 0xc7, 0xd4, 0x9b, 0xfe, 0xb6, 0xe0, 0x40, 0xb7,
	0xd2, 0xd2, 0xb6, 0x9a, 0x1d, 0x41, 0xf7, 0x3a, 0x15, 0x59, 0xe5, 0x87, 0x06, 0x72, 0x70, 0x69,
	0x5e, 0x9a, 0x54, 0x86, 0x68, 0x24, 0xa3, 0xa3, 0x24, 0xc1, 0x44, 0xf5, 0xb0, 0x99, 0x06, 0xe4,
	0x04, 0xe0, 0x2a, 0x9e, 0xe7, 0x28, 0xb2, 0x34, 0xff, 0x6e, 0xbc, 0x68, 0x31, 0x72, 0xa0, 0xda,
	0x19, 0x65, 0x85, 0xc7, 0x1a, 0x42, 0x66, 0x8f, 0x8a, 0xbb, 0x3c, 0x2b, 0x62, 0x59, 0xb8, 0xa7,
	0x8c, 0x6e, 0x31, 0x24, 0x84, 0x7e, 0x85, 0xd2, 0x7c, 0xee, 0xbb, 0x2a, 0xa0, 0x4d, 0xd1, 0x0f,
	0xd0, 0x6f, 0xec, 0xe4, 0xe4, 0x15, 0x38, 0xfa, 0xe5, 0x5b, 0xa1, 0x3d, 0xec, 0x9f, 0x91, 0x53,
	0x73, 0x2f, 0x4d, 0x10, 0x33, 0x11, 0xf4, 0x2d, 0x1c, 0x68, 0x02, 0x7f, 0xdc, 0x20, 0x17, 0xe4,
	0x21, 0xd8, 0x51, 0x96, 0x29, 0x7f, 0x5c, 0x26, 0x9f, 0x72, 0xe4, 0x69, 0x9a, 0xcf, 0xd0, 0x6c,
	0x42, 0x03, 0x7a, 0x6e, 0x36, 0x28, 0x7d, 0xe1, 0xe4, 0x25, 0x74, 0xd5, 0xc3, 0x34, 0x7c, 0xb4,
	0xd1, 0x50, 0x7e, 0x61, 0xfa, 0x3b, 0x8d, 0x60, 0xd0, 0xde, 0x06, 0x27, 0xaf, 0xc1, 0xad, 0xde,
	0x26, 0xf9, 0x68, 0x53, 0xad, 0xfe, 0xc8, 0xea, 0x28, 0x1a, 0x41, 0x5f, 0x55, 0x34, 0x82, 0x4f,
	0x00, 0x3e, 0xe7, 0xd9, 0x3a, 0xd6, 0x67, 0xaa, 0x75, 0xb7, 0x98, 0x5d, 0xe7, 0x4e, 0x17, 0xf0,
	0x20, 0x4a, 0x12, 0x5d, 0x85, 0x97, 0x45, 0xce, 0x91, 0xbc, 0x80, 0x7d, 0x89, 0x55, 0x81, 0x9d,
	0x03, 0xa8, 0xcf, 0xf2, 0xf8, 0xa6, 0x37, 0xb3, 0x19, 0x72, 0xae, 0x0a, 0xba, 0xac, 0x82, 0xd2,
	0xa6, 0xf1, 0x6a, 0x55, 0xac, 0xcc, 0xc1, 0x68, 0x40, 0x2f, 0xe0, 0xb0, 0x9a, 0xc0, 0xe8, 0x6d,
	0x2e, 0xcb, 0xda, 0xb8, 0x2c, 0xc9, 0x63, 0xcc, 0x8b, 0x5c, 0x15, 0x1e, 0x30, 0x83, 0xa8, 0x00,
	0x12, 0x25, 0x49, 0x5d, 0xc4, 0xc8, 0x3d, 0x85, 0x9e, 0xa1, 0x8c, 0xe2, 0xdd, 0xae, 0x55, 0x41,
	0xff, 0xaa, 0xfb, 0xec, 0x4f, 0x07, 0x9c, 0x89, 0x2a, 0x48, 0xde, 0x83, 0x37, 0x41, 0x61, 0x4e,
	0xab, 0x6e, 0xd3, 0x3e, 0x9a, 0xe0, 0xf1, 0xf6, 0x81, 0x71, 0xba, 0x47, 0xce, 0xc1, 0x9d, 0xa0,
	0xd0, 0x17, 0x52, 0x87, 0xb4, 0x76, 0x17, 0x90, 0x2d, 0x9b, 0x65, 0xda, 0x3b, 0xe8, 0x99, 0xed,
	0x90, 0xed, 0x3d, 0x04, 0x4f, 0x2b, 0xea, 0xde, 0x06, 0x75, 0xe2, 0x08, 0xb3, 0xff, 0x48, 0xfc,
	0x08, 0x7d, 0x39, 0x62, 0x75, 0x93, 0xc7, 0xf5, 0x90, 0x1b, 0xab, 0x0b, 0x9e, 0xec, 0xf2, 0x58,
	0x2a, 0xbe, 0x00, 0x68, 0x76, 0x44, 0x76, 0xae, 0x22, 0x08, 0x5a, 0xed, 0xef, 0x6d, 0x93, 0xee,
	0x7d, 0x75, 0xd4, 0xaf, 0xfc, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x30, 0x58, 0xd9,
	0xda, 0x05, 0x00, 0x00,
}
