sudo: false
language: go

go:
- 1.8

script:
  - go test

before_deploy:
  - bin/build release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "dist/*"
  skip_cleanup: true
  on:
    tags: true
